### ISSUE TITLE
Identify Bridge Transactions by ABI

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#102]
When a contract is created, identify this contract as a bridge contract. Recognizing future transactions to this contract will allow a user to follow this transaction to another chain. 

For example, a user could send POA to a bridge contract which fires an event to another contract on the away side to mint a new token. This transaction should be recorded and send the user to the appropriate explorer instance.

**Comment by KronicDeth** [comment]
Closed until we can determine a convention for indicating bridge contracts.  Nothing in the ABI indicates this currently.
