### ISSUE TITLE
Contributor sees new Blocks appear on the Block page without refreshing

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#104]
Blocks should appear on the `https://explorer-sokol.poa.network/en/blocks` page without refreshing.

**Comment by KronicDeth** [comment]
The websocket is already setup in the `ExplorerWeb.Endpoint`

https://github.com/poanetwork/poa-explorer/blob/c089e6831afe3cd30526673c9ca27722893e153c/apps/explorer_web/lib/explorer_web/endpoint.ex#L8

... but there are no channels setup in `ExplorerWeb.UserSocket`

https://github.com/poanetwork/poa-explorer/blob/c089e6831afe3cd30526673c9ca27722893e153c/apps/explorer_web/lib/explorer_web/channels/user_socket.ex#L4-L5

So, channels will need to be created that can be broadcasted to when the indexers see a new block.
