### ISSUE TITLE
User Workflow

### ISSUE THREAD

**Issue by katibest** [poanetwork/poa-explorer#107]

**Comment by katibest** [comment]
![poa-userflow](https://user-images.githubusercontent.com/20226535/38577592-599b6d8e-3ccf-11e8-951f-3095ba084f8f.jpg)

**Comment by acravenho** [comment]
1. Navigation -> Transactions -> Pending Transactions, Validated Transactions, All Transactions -> Details
2. Navigation -> List (list of all verified smart contracts -> Contract Detail Page (same view as account details)

https://etherscan.io/address/0x5ffc014343cd971b7eb70732021e26c35b744cc4
<img width="1309" alt="screen shot 2018-04-11 at 2 59 07 pm" src="https://user-images.githubusercontent.com/17620007/38637657-cd8918c0-3d99-11e8-9a5e-d7bf275885f1.png">

3. Navigation -> Accounts-> Details ->Unverifed contract-> Verification Form
4. Navigation -> Search -> Validated Smart Contract Name -> Details

**Comment by katibest** [comment]
I have all of these in the user flow except 
Navigation -> Accounts-> Details ->Unverified contract-> Verification Form

So from the Accounts page... you do an address and then you should be able to see to an unverified contract? I wonder if we have

Navigation -> Contracts -> Verified & Unverified (separate panels) -> Specific Contract

Unless we never want to see a list of unverified?

**Comment by acravenho** [comment]
An Address page view and a contract view are very similar:

Address: https://etherscan.io/address/0x9a4a90e2732f3fa4087b0bb4bf85c76d14833df1
Contract: https://etherscan.io/address/0x705ad59d611ffd9995b95a61007a49432db96cb4 (Unverified Contract)


We do not want unverified contracts on any list.

**Comment by katibest** [comment]
![poa-userflow-412](https://user-images.githubusercontent.com/20226535/38688129-51ea2f44-3e46-11e8-807d-bd63151e6693.jpg)
