### ISSUE TITLE
As a Contributor, I should see Internal Transaction Values as Ether instead of Wei.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#13]
Here is an example of the bug:
https://explorer-sokol.poa.network/en/transactions/0xbba93e1145f962ef1191a971e4db2d5eea30208dfb5e3588ce420c009e57a1d2/internal

The value should be in Ether.

**Comment by acravenho** [comment]
Yes, this was resolved. 😄

**Comment by jimmay5469** [comment]
Awesome, closing!
