### ISSUE TITLE
Coinmarketcap and CryptoCompare Historical Token Prices

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#148]
<h1>Updating Data</h1>
The goal for this issue is to pull in the current price data, market capitalization, and volume data of all tokens/coins supported on Coinmarketcap.com. This should updated every 5 minutes.

This information will be used on the following pages:

- transaction details page (USD value)
- account details page (USD Value)
- account details page (token balances)

`https://coinmarketcap.com/api/`

We should be storing `available_supply`, `market_cap_usd`, `24h_volume_usd`, `price_usd`, `symbol`, and `name` for each token/coin provided by Coinmarketcap.

<img width="456" alt="screen shot 2018-04-24 at 3 30 55 pm" src="https://user-images.githubusercontent.com/17620007/39209719-8c676c08-47d4-11e8-81ff-868c80e1439d.png">

<h1>Historical Data</h1>
We will also need to pull in the historical market capitalization, price, and volume data for supported instance of Explorer we are running from the CryptoCompare API. For our explorer instances, we should be pulling in either `POA` or `ETH` historical data.

This historical data will be used for the graph on the homepage. We will need to add a daily `open price`, `market cap`, and `volume` once per day using the Coinmarketcap.com API above.

Utilizing the below API call, we can store the `date`, `open` price, and average of the `volumeto` and `volumefrom`. To calculate the market capitalization of either `POA` or `ETH`, we will multiply the `available supply` from our Coinmarketcap data by the `price` for each day.

<a target="_blank" href="https://min-api.cryptocompare.com/data/histoday?fsym=BTC&tsym=USD&limit=90&aggregate=3&e=CCCAGG">`https://min-api.cryptocompare.com/data/histoday?fsym=BTC&tsym=USD&limit=90&aggregate=3&e=CCCAGG`</a>

**Comment by alexgaribay** [comment]
@acravenho What does the average of `volumefrom` and `volumeto` represent? Should I just store both of the two values and addition their their average?

**Comment by acravenho** [comment]
@alexgaribay Yes, that is a good idea. From what I can gather, the `to` and `from` represent the low and high of volume for that particular coin.

**Comment by alexgaribay** [comment]
@acravenho How far back in history should I go? The oldest record they have is July 17, 2010.

**Comment by alexgaribay** [comment]
@acravenho For clarification, we should fetch POA history or ETH history but not BTC even though the conversions usually involve BTC anyway?

**Comment by acravenho** [comment]
@alexgaribay Correct, we should be fetching the historical data for the main coin of our instance. If we are running a POA Core instance, the history data should reflect `POA`. The API provides `USD` rates which is exactly what we're looking for.

If a user deploys explorer for `ETH`, we should be fetching the history for `ETH` using the cryptocompare API.
