### ISSUE TITLE
Contributor sees Internal Transactions executed by a Contract on the Transaction Details page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#151]
Only transfers that are executed by a `Contract` are seen on the `Transaction Details` page. 

Example: [https://etherscan.io/tx/0xf21bca244b84acf82b173664080bc41fea832e92c57cb96323eb0a403373fad1](https://etherscan.io/tx/0xf21bca244b84acf82b173664080bc41fea832e92c57cb96323eb0a403373fad1)

We should not be displaying the `parent tx` value in the `internal transactions` table.

<img width="970" alt="screen shot 2018-04-25 at 4 49 51 pm" src="https://user-images.githubusercontent.com/17620007/39272133-0dfdde4e-48a9-11e8-94e9-337e240f6381.png">

**Comment by shweta037** [comment]
Is there any code for internal transactions...

**Comment by acravenho** [comment]
@shweta037 Can you describe what you mean? Yes, there is information on internal transactions on both the transaction details page and on the address page.
