### ISSUE TITLE
Smart Contract Verification

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#161]
1. Use Web3 Library `getCode` to get the bytecode of the Contract Address
2. Compile Source Code provided by Developer
3. Compare Compiled bytecode and given bytecode to verify contract.
4. If Verified, Store Source Code, ABI, Contract Name, Compiler Version, Libraries, Constructor Arguments, and Optimization in DB

**Comment by tmecklem** [comment]
So I understand this a little better, is this saying to use the same approach Web3 takes to get the bytecode of the address, or use Web3 directly to get the bytecode?

**Comment by gfreh** [comment]
Closing this issue cause it was merged with #68 to create #168, which will accommodate the scope of the former ones.
