### ISSUE TITLE
Developer verifies a Smart Contract against a specific compiler version

### ISSUE THREAD

**Issue by gfreh** [poanetwork/poa-explorer#198]
This issue is intended to continue the work from #168.

An initial set of tasks would include:
- Provide a way to compile the Solidity source code with different compiler versions.
- Update the explorer app so it can correctly verify a Smart Contract against the specific compiler version as selected by the contract's owner.
- Perhaps, it will be necessary to create a mechanism to update the compilers when new versions are launched.

**Comment by igorffs** [comment]
Thanks @gfreh!

I agree that we should remove the `0.1.1` and `0.1.2` from the list. 👍 And `0.1.3` error scheme is probably different from the other versions. I'll take a look so we can avoid the Phoenix error page in this scenario. 👍

**Comment by gfreh** [comment]
@igorffs I tested it this morning and now everything seems fine! I'm moving it to `Ready for Acceptance`. 

@acravenho would you like to take a look in it?

**Comment by acravenho** [comment]
LGTM!!! 👍

**Comment by gfreh** [comment]
The issue is solved and accepted thus I'll close it.
