### ISSUE TITLE
Handle large inputs on transactions page

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/poa-explorer#209]
Large input values on the transactions page can really mess up the layout.

Example:
![poa-explorer 2018-05-24 11-38-22](https://user-images.githubusercontent.com/781752/40496142-05c03268-5f47-11e8-9e65-5383f8ba3533.png)

**Comment by arthurra** [comment]
<img width="1369" alt="transaction details - input data" src="https://user-images.githubusercontent.com/1641169/40502674-b269f50a-5f59-11e8-9e7c-c2d4c5ef9266.png">

**Comment by arthurra** [comment]
![handle_large_input_content](https://user-images.githubusercontent.com/1641169/40506254-dc63338e-5f64-11e8-9675-69ab533f09ab.png)

**Comment by acravenho** [comment]
Looks good!!
