### ISSUE TITLE
UI Bug - Timezone should be uppercase

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#238]
In 3 months ago (Feb-15-2018 22:46:25 PM Etc/UTC), the `Etc` should be `ETC`.

<img width="799" alt="screen shot 2018-06-01 at 12 49 13 am" src="https://user-images.githubusercontent.com/17620007/40843283-70b258f2-657e-11e8-801e-d9db21fca552.png">

**Comment by arthurra** [comment]
@acravenho everything that we're finding online seems to be saying that ect/UTC is actually the correct abbreviation. Is there a reason for why we should be changing the formatting other than just how it looks?

**Comment by acravenho** [comment]
@arthurra You're completely right. My fault. I'll close the issue now.
