### ISSUE TITLE
Input field on Transaction Details page is too long

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#240]
<img width="1591" alt="screen shot 2018-06-01 at 8 22 22 am" src="https://user-images.githubusercontent.com/17620007/40843591-77d01baa-657f-11e8-8e06-97673ab0a9e7.png">

**Comment by katibest** [comment]
![screen shot 2018-06-06 at 10 49 47 am](https://user-images.githubusercontent.com/20226535/41045963-7b0cf2b0-6977-11e8-8cc0-dc38a69e89e3.png)
