### ISSUE TITLE
Addresses should fetch balance at a specific block, not time, and record that block

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/poa-explorer#243]
# Motivation

When the `Explorer.Indexer.AddressBalanceFetcher` fetches an `t:Explorer.Chain.Address.t/0` `fetched_balance`

https://github.com/poanetwork/poa-explorer/blob/4526874a8ceb1e5152f6b47001a20c9a5ba63c05/apps/explorer/lib/explorer/indexer/address_balance_fetcher.ex#L48-L50

it calls `EthereumJSONRPC.fetch_balances_by_hash/1`

https://github.com/poanetwork/poa-explorer/blob/4526874a8ceb1e5152f6b47001a20c9a5ba63c05/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex#L94-L111

which uses `latest` for the block number, which means the balance is as up-to-date as possible, but the problem is that we don't actually know which block number the balance is for then and instead we record a timestamp in `balance_fetched_at`.

`balance_fetched_at` kinda gives an idea of how out-of-date a balance may be, but it is difficult to correlate with the blocks, transactions, and internal transactions that may have changed the balance since the time is when we got the value, not the timestamp of block that the value is for.

# Proposed Changes

- [ ]  Instead of of using `latest` for the block parameter, feed in the desire block number from whatever is generating the address hash added to the `Explorer.Indexer.AddressBalanceFetcher`
- [ ] Replace `addresses.balance_fetched_at` with `addresses.balance_block_number`

## Follow-on Changes

Once we use `balance_block_number`, we can change `Explorer.Indexer.AddressBalanceFetcher` to to look ahead in the queue to see if there's a new block number queued and use the newest block number for the address.

Alternatively, we can move balances to a separate table and record the fetched balance at each block number.  We can combine this with the value generated in block mining/validating, transactions, and internal transactions to show a "cheque book" view of the address show which parts have been validated by the balance fetcher vs what we're showing from the indexed tables.  This will point out when our value calculations differ from the API.

**Comment by acravenho** [comment]
@KronicDeth I really like this idea. I thought of something similar this weekend but it revolved around running the indexer from current `block height` to `Genesis`. Balances will only need to be fetched on the first occurrence of an address, opposed to every occurrence.
