### ISSUE TITLE
nonce exceeds Postgres maxInt for PoW chain

### ISSUE THREAD

**Issue by zixuanzh** [poanetwork/poa-explorer#257]
Ran into this issue when adapting the explorer to work with PoW chain. Storing `nonce` as a `String.t()` but unsure if there are better fixes.

**Comment by zixuanzh** [comment]
PoA chains and some PoW chains currently set `nonce` to a small value, often zero.

**Comment by KronicDeth** [comment]
I have the nonce fixed on my `geth` branch.  I'm going to merge it in its partial state since it does not break parity support later today or next week after I finish my current task.
