### ISSUE TITLE
Error on 'mix ecto.create'

### ISSUE THREAD

**Issue by cmdhema** [poanetwork/poa-explorer#265]
My environments are
Linux ubuntu 16.04

elixir --version
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]
Elixir 1.6.5 (compiled with OTP 19)

psql -V
psql (PostgreSQL) 10.4 (Ubuntu 10.4-2.pgdg16.04+1)

When I command 'mix ecto.create' are return blow error messages

14:15:12.774 [error] GenServer #PID<0.282.0> terminating
** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (elixir) lib/keyword.ex:377: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: an exception was raised:
    ** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
        (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

I didn't edit any files. what can I do?

**Comment by igorffs** [comment]
Hey @cmdhema, try to setup your database configs [in Ecto configs](https://hexdocs.pm/ecto/Ecto.html#module-repositories):

https://github.com/poanetwork/poa-explorer/blob/32bd02e24b567dd16fca2980d9d3c695b9290bd5/apps/explorer/config/dev.exs#L3-L10

**Comment by KronicDeth** [comment]
Closing due to no feedback in a month.

**Comment by girish979** [comment]
I got the same error.
`dev@dev-Z370P-D3:~/code/poa-explorer/poa-explorer$ mix ecto.create && mix ecto.migrate 
==> ethereum_jsonrpc
Compiling 22 files (.ex)
Generated ethereum_jsonrpc app
==> explorer
Compiling 49 files (.ex)
Generated explorer app
==> explorer_web
Compiling 56 files (.ex)
Generated explorer_web app
==> indexer
Compiling 9 files (.ex)
Generated indexer app

11:18:36.301 [error] GenServer #PID<0.1299.0> terminating
** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (elixir) lib/keyword.ex:377: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: an exception was raised:
    ** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
        (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
`

**Comment by girish979** [comment]
@acravenho updated my environment settings

**Comment by acravenho** [comment]
Set up default configurations. cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs cp apps/explorer_web/config/dev.secret.exs.example apps/explorer_web/config/dev.secret.exs

1. Install dependencies. `mix do deps.get, local.rebar, deps.compile, compile`

2. Create and migrate database. `mix ecto.create && mix ecto.migrate`

3. Install Node.js dependencies. `cd apps/explorer_web/assets && npm install; cd -`

4. `cd apps/explorer && npm install; cd -`

5. Start Phoenix Server. `mix phx.server`

**Comment by dodikk** [comment]
>> 4. Create and migrate database. mix ecto.create && mix ecto.migrate

```
 mix ecto.create && mix ecto.migrate

18:29:37.709 [error] GenServer #PID<0.292.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
    (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
```

I am getting this error. @acravenho , are there any other setup steps between `[3]` and `[4]` omitted in the readme or in your list?

I've only been doing what you've suggested. What configs should I fix or what shell commands should I use to set the passwords properly?

**Comment by acravenho** [comment]
@dodikk Did you edit your dev.secret.exs file?

https://github.com/poanetwork/blockscout/blob/6a4d69d383632c9b1808dcaf16e76ac78f41cca5/apps/explorer/config/dev.secret.exs.example#L6-L9

**Comment by dodikk** [comment]
Well, that was not on your list.

When I followed the readme, I had an error for this config fix :

```
username: "adk",
password: "<something I've put in there>"
```

Am I supposed to have the username pinned to `"postgres"` ?
If so, adding some "can't touch this" comment might be a good idea.

**Comment by dodikk** [comment]
@acravenho , so I've fixed the mentioned config file (password only).
Still getting this 

```
adk@adk-VirtualBox:~/Applications/blockscout$ mix ecto.create && mix ecto.migrate

18:38:13.238 [error] GenServer #PID<0.292.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
    (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
```
