### ISSUE TITLE
Contributor sees the QR code for an Account hash.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#28]
QR code should be the same as on etherscan.io.

**Comment by arthurra** [comment]
<img width="1367" alt="address details - transactions" src="https://user-images.githubusercontent.com/1641169/40501830-0264f120-5f57-11e8-93ea-b8e9fd224183.png">

**Comment by arthurra** [comment]
Etherscan.io screenshot: 

<img width="1280" alt="etherscan_address_qr_code" src="https://user-images.githubusercontent.com/1641169/40509761-89423714-5f68-11e8-9e07-1de95000e341.png">

**Comment by arthurra** [comment]
**Observations:**
* The Etherscan QR code only stores a text string with the account number

**Available tools:**
* Elixir: [qrcode - Boshan Sun](https://github.com/sunboshan/qrcode)
* Erlang: [qrcode - Francois Ribemont](https://gitlab.com/Pacodastre/qrcode)

**Comment by acravenho** [comment]
Good to know, thanks @arthurra. I'm trying to find out which is better. From a usability standpoint if you are sending someone your wallet address having the text string makes it very easy from a smartphone vs just having the url. It's easier to copy and paste than to delete characters.

**Comment by arthurra** [comment]
That seems to be the consensus from what I'm finding as well. 👍

**Comment by arthurra** [comment]
There may be potential for us to use a URI scheme to encode additional information along with an address if that is valuable. However, I admittedly have limited info on this topic.

**Comment by arthurra** [comment]
WIP on branch `address-qr-code-#28`
