### ISSUE TITLE
Deployed in local, the interface is not same as https://poaexplorer.com/, why?

### ISSUE THREAD

**Issue by StormSpirit22** [poanetwork/poa-explorer#287]
I've downloaded the explorer source code and deployed in local, the front-end interface is far away from https://poaexplorer.com/, is it much code didn't commit yet? This is my local web page:
![image](https://user-images.githubusercontent.com/6985964/41387620-6acfd6d0-6fba-11e8-94dd-ba7aaafb2b97.png)

**Comment by acravenho** [comment]
poaexplorer.com is the community explorer. Is there something you liked about that interface that you don't see here?

**Comment by StormSpirit22** [comment]
Does poaexplorer.com's code is same as the github's code ?  The poaexplorer.com, its interface is more concise than my local interface, just prefer the community explorer's layout.

**Comment by acravenho** [comment]
No, poaexplorer.com's code is located here: https://github.com/acravenho/poaexplorer.com. 

We will be updating this user interface very soon for a more concise look and feel.

**Comment by StormSpirit22** [comment]
Thanks a lot!
