### ISSUE TITLE
Contributor sees a graph of POA Network value, Market Capitalization, and graph on homepage.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#29]
Chart of value should include 30 days of history by default, with time as the X axis, and two Y-axes, one showing the market value in USD, and the other showing market cap. Market cap is defined using the latest `available_supply` multiplied by each historical price point.

<img width="1202" alt="screen shot 2018-04-01 at 5 47 33 pm" src="https://user-images.githubusercontent.com/17620007/38177845-d2960e44-35d4-11e8-91a8-35c9ed1a47d6.png">
<img width="524" alt="screen shot 2018-04-01 at 5 47 45 pm" src="https://user-images.githubusercontent.com/17620007/38177846-d2c0c472-35d4-11e8-8c7f-481850383219.png">

**Comment by jimmay5469** [comment]
We are going to do the live update of these statistics using Phoenix channels as part of a later issue. It looks like #33 already exists and should suffice.
