### ISSUE TITLE
Age fields should ascend in real-time across the explorer

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/poa-explorer#313]

**Comment by KronicDeth** [comment]
For efficiency, this should be implemented as the Phoenix Channel sending the latest block number and the client-side code should recalculate the ages on the page.  Having subscriptions for each specific "age" owner will likely be inefficient.

**Comment by jimmay5469** [comment]
Totally agree, and that was my intention. I was just writing the story from the user's point of view.

**Comment by jimmay5469** [comment]
I burrowed some wording from another card which should hopefully make the title of this card more clear.
