### ISSUE TITLE
Last Updated in Block does not contain same styles as other Labels

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#317]
On the account overview the `Last Updated in Block` does not contain the same styles as the Labels above.

<img width="520" alt="screen shot 2018-06-20 at 1 27 18 pm" src="https://user-images.githubusercontent.com/17620007/41674333-b2f7bdce-748d-11e8-95be-f3b21ab455e4.png">

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:

### Steps to reproduce

Pull master and view http://localhost:4000/en/addresses/0xe897aa11cc38f8723f844cbb098b79f7617d6cf5/transactions

### Expected behaviour

We should see the same style as the labels above.

**Comment by KronicDeth** [comment]
That's my bad.  I added that in https://github.com/poanetwork/poa-explorer/pull/283 and missed the first cell was a `th` and not `td`.  Maybe I missed a style change while it was awaiting review and since it was new code it didn't conflict on merge. :man_shrugging:
