### ISSUE TITLE
no match of right hand side value: {:error, :closed}

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#319]
```
[error] realtime index stream exited. Restarting
[error] Task #PID<0.4976.0> started from Explorer.Indexer.BlockFetcher terminating
** (MatchError) no match of right hand side value: {:error, :closed}
    (explorer) lib/explorer/indexer/block_fetcher.ex:293: Explorer.Indexer.BlockFetcher.realtime_task/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<13.10000346/0 in Explorer.Indexer.BlockFetcher.handle_info/2>
    Args: []
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: Local Mac

### Steps to reproduce

1. Started Indexer
2. Reached Block 2,800,000
3. Aborted
4. Restarted Indexer
5. Received the above error in between blocks `3073933 - 3073924` and `3073913 - 3073904`

**Comment by KronicDeth** [comment]
https://github.com/poanetwork/poa-explorer/blob/027ad14df0744292534756779168769fbc284839/apps/explorer/lib/explorer/indexer/block_fetcher.ex#L292-L296

Line 293 is checking the response from calling the JSONRPC on Parity.  `{:error, :closed}` means the TCP connection was closed by Parity.  As the log say, it is already restarting the task, so it is working as expected.  We still want the log to happen though, so we can be notified if the Parity nodes continually close our connections in which case we would check their status or upscale them.

I would leave the behavior as is unless you want a clearer log message.

**Comment by acravenho** [comment]
I think the message is fine. I had never seen the message before and wanted to make sure it wasn't anything that needed attention. Indexer is running great.
