### ISSUE TITLE
Indexer stuck at block 836686 & 1044316

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#341]
On previous runs of the Indexer we've noticed they tend to get stuck in the 800k-900k block range. The Indexer that @KronicDeth deployed is currently stuck at 836686. My indexer is currently stuck at 911005. 

This issue may be related to #340. 

As @KronicDeth said "What I'm guessing is the root causes is we know the 800k blocks time out a lot.  When those timeouts occur, we requeue them, but there is some problem where when we requeue, we're not chunking properly and they all get into one big chunk, which gets us the 6537 element array"

### Steps to reproduce

Run the indexer from chain tip. This process takes 10-12 hours.

**Comment by acravenho** [comment]
Here is where we are stuck currently: http://sokb-explorer-sokol-elb-1563248932.us-east-1.elb.amazonaws.com/en/blocks?block_number=911050. The indexer restarts after hitting this wall.

This may be related to #340

**Comment by acravenho** [comment]
Here is a snippet from running the indexer on my local machine for 1 hour from chain tip:

```
[debug] got blocks 3306771 - 3306762
[debug] got blocks 3306751 - 3306742
[debug] got blocks 3306761 - 3306752
[debug] got blocks 1010793 - 1010784
[debug] fetching 49 transaction receipts
[debug] got blocks 1010803 - 1010794
[debug] fetching 98 transaction receipts
[debug] fetching internal transactions for 10 transactions
[debug] got blocks 3306731 - 3306722
[debug] fetching internal transactions for 10 transactions
[debug] got blocks 3306651 - 3306642
[debug] got blocks 3306671 - 3306662
[debug] got blocks 3306661 - 3306652
[debug] got blocks 3306691 - 3306682
[debug] got blocks 3306701 - 3306692
[debug] fetching 21 transaction receipts
[debug] got blocks 3306721 - 3306712
[debug] got blocks 3306681 - 3306672
[debug] got blocks 1010743 - 1010734
[debug] fetching 49 transaction receipts
[debug] got blocks 1010723 - 1010714
[debug] fetching 49 transaction receipts
[debug] got blocks 1010773 - 1010764
[debug] fetching 98 transaction receipts
```

Everything was running great until we got down to a spam section (< `1,100,000`) where every block was full. In this section, it looks like one of the indexer processes decided to start over from `3,300,300`. We were on block `1,01x,xxx` running perfectly and then as you can see by the snippet it started indexing again from the start even though we've already indexed those blocks.

**Comment by KronicDeth** [comment]
`3,300,300` is around `latest`, so what it is doing is probably restarting the genesis task.  When it does that, it asks for `latest` using JSONRPC and using the number for `latest` finds all missing blocks between `latest` and `0` using `Explorer.Chain.missing_block_number(latest..0)`.  Since it was not getting the newest blocks while it was restarting, it has missing blocks both near `latest` and around `1,01x,xxx` where it died and restarted.  So, your log makes sense in the face of a restart of the task.

**Comment by KronicDeth** [comment]
This may have been fixed by #411.  Waiting to get below block 800,000 to be sure.

**Comment by KronicDeth** [comment]
@acravenho my indexer run has reached block 0 using the changes from #419, which is merged to master now.  Can we close this?

**Comment by acravenho** [comment]
@KronicDeth yes, let's close it. The deployed version is at 0 as well. 👍
