### ISSUE TITLE
Indexer.Sequence processes leak

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/poa-explorer#387]
While investigating #341, I started up 

### Steps to reproduce

1. `DEBUG_INDEXER=1 iex -S mix`
2. `:observer.start()`
3. Wait.
4. Observe Process count

### Actual behaviour

The number of processes as reported by Observer keeps increasing and looking at the Processes tab, it is filled with an ever growing number o `Elixir.Indexer.Sequence:-start_link/3-fun-0/-/0` entries, with only 1 have > 2 reductions

![screen shot 2018-07-10 at 12 29 23 pm](https://user-images.githubusercontent.com/298259/42526959-e9a83a60-843c-11e8-8dfd-52811a6635b4.png)

### Expected behaviour

There should only ever be 2 `Elixir.Indexer.Sequence:-start_link/3-fun-0/-/0` entries as there are 2 `Sequence.start_link` calls in the code base.

1. For the genesis task
   https://github.com/poanetwork/poa-explorer/blob/8881d9e4de908787b2cd70216e1c79d326b7f9be/apps/indexer/lib/indexer/block_fetcher.ex#L185-L194
2. For the realtime task
  https://github.com/poanetwork/poa-explorer/blob/8881d9e4de908787b2cd70216e1c79d326b7f9be/apps/indexer/lib/indexer/block_fetcher.ex#L296-L300

### Solution

Switch `Sequence` from using an `Agent` to being a normal `GenServer`, so we can `Process.flag(:trap_exit, true)` in `init/1`.

**Comment by KronicDeth** [comment]
The node eventually ran out of memory:

```
debug] got blocks 2831380 - 2831371
eheap_alloc: Cannot allocate 14104570056 bytes of memory (of type "old_heap").

Crash dump is being written to: erl_crash.dump...
```

**Comment by igorffs** [comment]
@KronicDeth we can also make the current GenServer manages both Sequencers. We'd need to start both sequencers in the `BlockFetcher.init`, store their PIDs for later usage in its state and shutting them down when the `BlockFetcher` is shut down.  \o 

The essence is the same, but we wouldn't need to change the Sequence for a GenServer.
