### ISSUE TITLE
Support for Address Balance History

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#401]
Distributed ledgers should provide historical data regarding address balances. Our explorer does not currently support this type of functionality. 

Historical balances provide:
- internal error checking of addresses
- improved user experience

### Tasks

- [x] store address balance by block in db
- [ ] frontend experience of balance history similar to accounting software (moved to issue #433)

### Expected behaviour

We should expect a frontend experience similar to a QuickBooks or other accounting app. This will provide a thorough overview of an address's balance history.

**Comment by KronicDeth** [comment]
Closing because the second part has moved to #433 and the BE part has been resolved by #431.
