### ISSUE TITLE
Network dropdown overlaps on homepage

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#405]
The network dropdown has a z-index issue on the homepage where it overlaps with the stats box.

<img width="937" alt="screen shot 2018-07-15 at 11 50 59 am" src="https://user-images.githubusercontent.com/17620007/42735619-5eabc9a8-8825-11e8-92e9-ab62d70aa578.png">

**Comment by igorbarinov** [comment]
Thank you for creating the issue
