### ISSUE TITLE
Deploy- Refused to connect violates Content Security Policy

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#414]
I receive the following error on the deployed version of explorer:

```
Refused to connect to 'ws://sokll-explorer-sokol-elb-852408732.us-east-1.elb.amazonaws.com/socket/websocket?locale=en&vsn=2.0.0' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:*
```

### Environment

* Operating System: Linux

### Steps to reproduce

Deploy explorer via `https://github.com/poanetwork/poa-explorer-infra`

**Comment by polygon-kyle** [comment]
hi - what was the fix here?  I have a block explorer UI that has encountered this same error.  https://explorer-ui.cardona.zkevm-rpc.com/
