### ISSUE TITLE
Denormalize transactions table to add created contract address hash

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#430]
We're seeing some optimization issues with having the `created_contract_address_hash` solely in the `internal_transactions` table. The easiest solution would be to add this column to the `transactions` table as well.

With a full Ethereum Mainnet Index, we will surely see optimization issues so it's best to make this change now.

**Comment by KronicDeth** [comment]
@acravenho are we sure we can only create 1 contract for a given transaction?

**Comment by acravenho** [comment]
@KronicDeth, only 1 contract can be created by a single parent transaction but internally there can be multiple contracts created. 

Here is an example: https://kovan.etherscan.io/tx/0xf87057258210058dbac4dbcace0fa70ad117814345cf0291e5ac5443acc9986b

In the parent transaction, a contract is deployed and immediately after that deployed contract created another contract as seen in the internal transactions tab.

**Comment by jimmay5469** [comment]
@acravenho @KronicDeth it looks like we've figured out a query that can solve the issue without denormalization. We would need to port it to Ecto which will take some work. Is the right thing to do porting this query or is the right thing to do moving forward with the denormalization? We can hop on a call to discuss if necessary.

**Comment by acravenho** [comment]
@jimmay5469 The reason this query was originally created is to support contracts that deploy other contracts. Denormalizing the `contracted_create_address` into the parent transaction table doesn't solve this query IMO. 

I think it's best if we optimize the query by porting it to Ecto.

**Comment by jimmay5469** [comment]
I opened #477 to track the optimization work and am de-prioritizing this issue.
