### ISSUE TITLE
Improve Token Transfers cards in the Transactions tab in the Address page

### ISSUE THREAD

**Issue by gfreh** [poanetwork/poa-explorer#478]
This issue is intended to make some changes to the Token Transfers cards in the Transactions tab in the Address page, as implemented by #75. 

### Changes on the Address page:
- If the parent Transaction **IS NOT** sending POA, the Token Transfer card should display:
  - A line with the parent Transaction hash and a link to the Transaction details
  - A line for each token transfer in that transaction that is related to the associated Address with:
    - Token Transfer `from` Address -> Token Transfer `to` Address
    - Amount of Token transferred and the Token symbol
  - A line with:
    - The label:
      - `in` if the associated Address is receiving tokens.
      - `out` if the associated Address is sending tokens.
      -  `-` or no label if the associated Address is both sending **and** receiving tokens.
    - The age of the parent Transaction.
    - The block in which the parent Transaction took place.
- If the parent Transaction **IS** sending POA, the Token Transfer card should display:
  - A line with the parent Transaction hash, a link to the Transaction details and the amount o POA transferred
  - A line with the parent Transaction `from` Address -> parent Transaction `to` Address and the fee
  - A line with:
    - The label:
      - `in` if the associated Address is receiving POA.
      - `out` if the associated Address is sending POA.
      -  `-` or no label if the associated Address is **neither** sending **nor** receiving POA.
    - The age of the parent Transaction.
    - The block in which the parent Transaction took place.
  - A separator line
  - A line for each token transfer in that transaction that is related to the associated Address with:
     - Token Transfer `from` Address -> Token Transfer `to` Address
     - Amount of Token transferred and the Token symbol
- If there is no Token Transfer associated with the parent Transaction, the behavior remains the same as today.

For contracts addresses, the behavior should be very similar to the one mentioned above:
- If the call to the contract **IS NOT** sending POA, we show only the Token Transfers list (with the transfers related to that token) and a `-` label or no label at all. 
- On the other hand, if the call **IS** sending POA, we show the parent Transaction info, the list of Token Transfers and an `IN` label. 

**Example:**
![tokentransfer](https://user-images.githubusercontent.com/1440642/43345361-a7035b74-91c3-11e8-95f4-cbf78743c8af.jpg)

Disclaimer: The image above does not have all the elements as described by the bullets.

**Comment by gfreh** [comment]
@acravenho could you please take a look in the acceptance criteria above to confirm everything is ok? 

We also have an additional question: consider we are viewing the Contract Address details page, associated with the Token that has been transferred in a specific transaction. Currently, we show the parent Transaction info and all the Token Transfers below it (see image below).

![screen shot 2018-07-27 at 19 15 42](https://user-images.githubusercontent.com/1440642/43348651-8619a9c8-91d1-11e8-8d79-5af621053fec.png)

With the changes we've discussed, what is the expected behavior?

As far as we understood, if the call to the contract **IS NOT** sending POA, we show only the Token Transfers list and a `-` label or no label at all. On the other hand, if the call **IS** sending POA, we show the parent Transaction info, the list of Token Transfers and an `IN` label. Is that correct?

**Comment by gfreh** [comment]
@acravenho thanks! 

Regarding the links you've mentioned, implementing them is currently in the scope of the issue #51.

- Token links should redirect to the Token/Address Details page
  - In the Tx details page, when clicking on the Token Symbol/Name.
  - In the Address Tx List, when clicking on the Token Symbol/Name.
  - In the Address Token balances dropdown list, when clicking on a Token

But, since it depends on some issues that haven't been started (issue #50, for instance), we're wondering if it's a good idea to create a new issue to implement all those links. What do you think?

**Comment by acravenho** [comment]
@gfreh Yes, that would be fine to create a new issue for these links.
