### ISSUE TITLE
Decode input data and add addresses to the balance updater

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#488]
This issue is related to #378 and covers the task for decoding the input data and adding addresses to the indexer balance updater queue.

If an address appears in the input data there is a chance that its balance could be changed. These addresses should be added to the balance updater queue. 

Here is a typical input data:

```
0xa007155200000000000000000000000000000000000000000000000000000000000000a4000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000004
```

From this data, the first 10 characters are the `methodID`. In this case, it would be `0xa0071552`.

After the `methodID`, every 64 characters needs to be decoded to be checked for an address.

```
MethodID: 0xa0071552
[0]: 00000000000000000000000000000000000000000000000000000000000000a4
[1]: 0000000000000000000000000000000000000000000000000000000000000002
[2]: 0000000000000000000000000000000000000000000000000000000000000001
[3]: 0000000000000000000000000000000000000000000000000000000000000004
```
No addresses appear here.

**Comment by alexgaribay** [comment]
As discussed in Slack. Internal transactions are created whenever there is value transferred between addresses. We are already checking internal transactions for addresses. As such, this issue is being closed.
