### ISSUE TITLE
Runaway postgres processes

### ISSUE THREAD

**Issue by tmecklem** [poanetwork/poa-explorer#491]
I frequently have runaway postgres processes after stopping the indexer, and they block other activity (like adding a column, etc). The processes seemingly need to be killed every time. Most recently, I ran the indexer overnight, and there were two stuck processes this morning that continued running for several hours. Both were running this query:

> SELECT a0."hash", b4."number" FROM "addresses" AS a0 LEFT OUTER JOIN "internal_transactions" AS i1 ON a0."hash" IN (i1."created_contract_address_hash",i1."from_address_hash",i1."to_address_hash") LEFT OUTER JOIN "logs" AS l2 ON l2."address_hash" = a0."hash" LEFT OUTER JOIN "transactions" AS t3 ON t3."hash" IN (i1."transaction_hash",l2."transaction_hash") OR a0."hash" IN (t3."from_address_hash",t3."to_address_hash") LEFT OUTER JOIN "blocks" AS b4 ON (b4."hash" = t3."block_hash") OR (b4."miner_hash" = a0."hash") LEFT OUTER JOIN "balances" AS b5 ON (b5."address_hash" = a0."hash") AND (b5."block_number" = b4."number") WHERE ((NOT (b4."number" IS NULL) AND b5."address_hash" IS NULL) AND b5."block_number" IS NULL) GROUP BY a0."hash", b4."number"

### Environment

* Elixir & Erlang/OTP versions (`elixir -v`): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.5 (compiled with OTP 19)
```
* Operating System: macOS High Sierra 10.13.6
Postgres: 10.4

### Steps to reproduce

* Start the indexer on an empty database and let it run for a while (overnight is usually enough to reproduce)
* Stop the indexer
* Note there are one or more postgres OS processes consuming as much CPU at they can
* Execute `select * from pg_stat_activity where datname = 'explorer_dev'` and note several pg processes executing the same query noted at the beginning of the issue description.

### Expected behaviour

Stopping the elixir processes should eventually result in the postgres processes winding down

### Actual behaviour

The postgres processes continue to consume CPU resources seemingly indefinitely.

**Comment by KronicDeth** [comment]
@tmecklem are you killing the node with Ctrl+C Ctrl+C?

**Comment by KronicDeth** [comment]
@josevalim is node killing with Ctrl+C Ctrl+C something that is interceptable, so that Ecto/Postgrex can handle clean shutdown of Repo.stream queries?  Should I file this as an Ecto or Postgrex bug?

**Comment by KronicDeth** [comment]
I'll add more information about what I think is happening: some of the `Repo.stream` calls are very long running, which is why we made them use `Repo.stream`. When you kill the node, which is usually how we all stop the indexer, there is a chance of the `Repo.stream` queries, which @tmecklem original query is one of, not cleaning up.  This appears to be normal according to [DBA StackExchange](https://dba.stackexchange.com/a/81424) and the only way to make it clean up is to explicitly tell Postgres to cancel or terminate the backend as otherwise, the query won't check if the client is still there until it tries to write data to the client, which for the long queries may be awhile.  It might also be that the check never happens because of how `Repo.stream` is implemented that it must ask for the data.  I haven't been able to follow the code in Ecto far enough to be sure.

**Comment by josevalim** [comment]
@KronicDeth we need to make a distinction between `System.halt` and `System.stop`. If the issue persists with `System.stop`, then that's a postgrex bug. However, if the issue only happens with System.halt, then you do have to trap it: http://erlang.org/doc/man/os.html#set_signal-2

**Comment by KronicDeth** [comment]
The query itself is super slow, taking minutes for each component even, so as part of fixing this, I'm working on tuning the pieces.

**Comment by KronicDeth** [comment]
The different queries times are terrible

`blocks.miner_hash`
---
```sql
SELECT addresses.hash AS address_hash, blocks.number AS block_number
FROM addresses
       LEFT OUTER JOIN blocks
         ON blocks.miner_hash = addresses.hash
       LEFT OUTER JOIN balances
         ON balances.address_hash = addresses.hash AND balances.block_number = blocks.number
WHERE blocks.number IS NOT NULL AND
      balances.address_hash IS NULL AND
      balances.block_number IS NULL
GROUP BY addresses.hash, blocks.number
```

Total query runtime: 1 min. `272554` rows affected.

```sql
SELECT blocks.miner_hash AS address_hash, blocks.number AS block_number
FROM blocks
WHERE NOT EXISTS (
            SELECT 1
            FROM balances
            WHERE balances.address_hash = blocks.miner_hash AND
                  balances.block_number = blocks.number
    )
```

Total query runtime: 26 secs. `272554` rows affected.



`transactions.from_address_hash`
---

```sql
SELECT transactions.from_address_hash AS address_hash, blocks.number AS block_number
FROM transactions
INNER JOIN blocks
  ON blocks.hash = transactions.block_hash
WHERE NOT EXISTS (
    SELECT 1
    FROM balances
    WHERE balances.address_hash = transactions.from_address_hash AND
                  balances.block_number = blocks.number 
  )
```

Total query runtime: 7 min. `3016696` rows affected.

```sql
SELECT transactions.from_address_hash AS address_hash, transactions.block_number AS block_number
FROM transactions
WHERE NOT EXISTS (
    SELECT 1
    FROM balances
    WHERE balances.address_hash = transactions.from_address_hash AND
                  balances.block_number = transactions.block_number
  )

Total query runtime: 7 min. `3016744` rows affected. 

```sql
SELECT transactions.from_address_hash AS address_hash, transactions.block_number AS block_number
FROM transactions
EXCEPT
SELECT balances.address_hash AS address_hash, balances.block_number AS block_number
FROM balances
```

Total query runtime: 8 min. `2492723` rows affected.

`balances.*`
---

```sql
SELECT *
FROM balances;
```

Total query runtime: 16 min. `4460271` rows affected.


Given these minute long times, I'm going to try changing how `balances` are stored

1. Change `balances.value` to `null: true`
2. Add index `create(unique_index(:balances, [:address_hash, :block_number], where: "value IS NULL"))`
3. Always create `balances`, but when we don't know they `value`, set `value` to `null`.
4. Use instead from (2) to find the balances that need to be fetched

Hopefully, the query in (4) will be faster than 7 minutes.
