### ISSUE TITLE
Everything Works/ Compiles Up to mix ecto.create 

### ISSUE THREAD

**Issue by alexacostarua** [poanetwork/poa-explorer#492]
When I run: mix ecto.create && mix ecto.migrate
it returns...
10:41:54.659 [error] GenServer #PID<0.505.0> terminating
** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (elixir) lib/keyword.ex:377: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Explorer.Repo couldn't be created: an exception was raised:
    ** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
        (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

Environment:
PostgreSQL 10.4-2
Erlang/OTP 21
Elixir 1.6.6 (compiled with OTP 19)
Nodejs v10.7
Npm v 6.1

* Operating System:
Ubuntu 16.04 LTS

The usage is also going to be for geth (not parity)

Please let me know how I can fix this issue.  This is the best block explorer out there by far.  I don't want to give up on this project and run some bs ether-party explorer.

**Comment by acravenho** [comment]
@alexacostarua Thank you for your remarks:)

Please see #480. You should find a resolution there.

**Comment by alexacostarua** [comment]
Very helpful!  Works perfectly now.
