### ISSUE TITLE
Can you use this explorer with your private blockchain?  Or Geth RPC endpoint?

### ISSUE THREAD

**Issue by alexacostarua** [poanetwork/poa-explorer#498]
I finally got this legendary block explorer working, the functionality and look are truly amazing!   I was wondering if its possible to add your own block chain to it or aka a geth rpc endpoint.  If its possible.  Where would I add this?

**Comment by alexgaribay** [comment]
Yes. You'll need to set two environment variables.

```
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=your_rpc_endpoint
```

Note that you might have issues if you're node isn't configured to send internal transactions with that same endpoint.

**Comment by alexacostarua** [comment]
Ok.  How does that work don't environment variables last until you close the app?  Would it be possible to replace the default main net rpc end point (POA Mainnet) with my own end point.  So it just loads up automatically to my endpoint every time I run it?   Would be great if you could tell me the destination of that.

**Comment by alexgaribay** [comment]
Assuming you're deploying from a unix-based OS, you can set these values in your `~/.bashrc` file.

```
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=your_roc_endpoint
```

The app will read these values every time it is run.

**Comment by alexacostarua** [comment]
Ok.  I used nano ~/.bashrc and added the export ETHEREUM_JSONRPC_VARIANT=geth
and export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545 .  After running mix phx.server ... It returned the error [error] GenServer ExplorerWeb.EventHandler terminating
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1474: anonymous fn/0 in Enum.max_by/2
    (explorer_web) lib/explorer_web/notifier.ex:18: ExplorerWeb.Notifier.handle_event/1
    (explorer_web) lib/explorer_web/event_handler.ex:26: ExplorerWeb.EventHandler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:chain_event, :blocks, []}
State: []
[error] GenServer ExplorerWeb.EventHandler terminating
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1474: anonymous fn/0 in Enum.max_by/2
    (explorer_web) lib/explorer_web/notifier.ex:18: ExplorerWeb.Notifier.handle_event/1
    (explorer_web) lib/explorer_web/event_handler.ex:26: ExplorerWeb.EventHandler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:chain_event, :blocks, []}
State: []
[error] GenServer ExplorerWeb.EventHandler terminating
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1474: anonymous fn/0 in Enum.max_by/2
    (explorer_web) lib/explorer_web/notifier.ex:18: ExplorerWeb.Notifier.handle_event/1
    (explorer_web) lib/explorer_web/event_handler.ex:26: ExplorerWeb.EventHandler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:chain_event, :blocks, []}
State: []
[error] GenServer ExplorerWeb.EventHandler terminating
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1474: anonymous fn/0 in Enum.max_by/2
    (explorer_web) lib/explorer_web/notifier.ex:18: ExplorerWeb.Notifier.handle_event/1
    (explorer_web) lib/explorer_web/event_handler.ex:26: ExplorerWeb.EventHandler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:chain_event, :blocks, []}
State: []
[debug] Updating cached exchange rates
[error] GenServer ExplorerWeb.EventHandler terminating
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1474: anonymous fn/0 in Enum.max_by/2
    (explorer_web) lib/explorer_web/notifier.ex:18: ExplorerWeb.Notifier.handle_event/1
    (explorer_web) lib/explorer_web/event_handler.ex:26: ExplorerWeb.EventHandler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:chain_event, :blocks, []}
State: []
---------------------------------------------------------------------------------------------------
The localhost:4000 still returns with a view into the POA main net and not my RPC endpoint.  I've added the --rpccorsdomain "localhost:4000"  to my geth node too.  What am I missing here?  And wouldn't the change in endpoints be located somewhere within the poaexplorer files not the bashrc??
