### ISSUE TITLE
Developer sees if a Contract has been Verified previously.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#67]
If the Contract was previously Verified, the tab will be labeled “Contract Source”. If the Contract has not been verified it will be labeled “Verify Contract”.

[Example](https://etherscan.io/address/0xf244176246168f24e3187f7288edbca29267739b)

<img width="726" alt="screen shot 2018-03-18 at 9 08 56 pm" src="https://user-images.githubusercontent.com/17620007/37573649-9a4c1414-2af0-11e8-9ebe-83fddeb5cca6.png">

**Comment by gfreh** [comment]
I'm closing this issue because it was solved by #168.
