### ISSUE TITLE
If Contract is not Verified, Developer sees options to Verify Contract.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#68]
Fields include: 

- Contract Address (pre-filled)
- Contract Name
- Compiler Version (dropdown)
- Optimization
- Solidity Contract Code

[Example](https://etherscan.io/verifyContract?a=0xe58af3dcbe423c1e330f9d6e61cd47cb530239ac)

<img width="1123" alt="screen shot 2018-03-18 at 9 10 30 pm" src="https://user-images.githubusercontent.com/17620007/37573674-db02ef1e-2af0-11e8-9c53-052eed8133ce.png">

**Comment by gfreh** [comment]
Closing this issue cause it was merged with #161 to create #168, which will accommodate the scope of the former ones.
