### ISSUE TITLE
If Contract has been Verified, Developer sees Contract Source Code, ABI, and Contract Creation Code

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#69]
[Example](https://etherscan.io/address/0xf244176246168f24e3187f7288edbca29267739b#code)

<img width="1180" alt="screen shot 2018-03-18 at 9 12 20 pm" src="https://user-images.githubusercontent.com/17620007/37573694-13c58df2-2af1-11e8-91a7-a3e3c8ac1429.png">

**Comment by gfreh** [comment]
@acravenho I've tested it and it seems to be ok! Do you wanna take a look before we move this issue to done?

**Comment by acravenho** [comment]
LGTM 👍

**Comment by amandasposito** [comment]
I'm closing this issue because it was solved by https://github.com/poanetwork/poa-explorer/pull/247
