### ISSUE TITLE
When Verifying a Contract the Developer can pick any Compiler Version [to be deleted ✂️]

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#74]
The first iteration should only include 1 compiler version. Later, we must include all compiler versions.

[Example](https://etherscan.io/verifyContract?a=0xe58af3dcbe423c1e330f9d6e61cd47cb530239ac)

<img width="1103" alt="screen shot 2018-03-18 at 9 17 12 pm" src="https://user-images.githubusercontent.com/17620007/37573775-cbf83366-2af1-11e8-9135-88887b251840.png">

**Comment by gfreh** [comment]
I'm closing this issue because it has already been solved by issue #198.
